### ISSUE TITLE
fail on windows

### ISSUE THREAD

**Issue by mastilver** [michaelzoidl/babel-root-import#10] opened 2016-02-13 23:19 UTC
version 1.x was working fine for me
After a migration to babel@6 and update of this package

It's just because it's returning `/` instead of '\'
PR is on its way ;)

**Comment by michaelzoidl** [comment] 2016-02-15 07:36
Oh.. well, i didn't test this module on windows.
Yay, if it's just a minor i will merge the PR as fast as i can :)
Thanks

**Comment by mastilver** [comment] 2016-02-15 10:39
I didn't have must time over the week-end
I will try to work on it on Tuesday

**Comment by michaelzoidl** [comment] 2016-02-15 10:41
No haste :) as long as the plugin works in your project its perfect.

**Comment by jmaguirrei** [comment] 2016-02-17 12:27
Hello, does this plugin works for windows now? Thanks

**Comment by michaelzoidl** [comment] 2016-02-17 12:29
I think not yet... @mastilver manages this issue
@mastilver do you've problems? Otherwise i could also manage this issue :)

**Comment by mastilver** [comment] 2016-02-17 12:33
@jmaguirrei version 1.1 is working with babel@5


>  Otherwise i could also manage this issue :)

@michaelzoidl go for it, I've written some code but it's acting weird

**Comment by michaelzoidl** [comment] 2016-02-17 12:59
Ok cool.. 
To sum up this issue: the problem is the replacing of the `~` with the root-path - at this moment it will be replaced with the path like `/User/michaelzoidl/myproject/foo.js`.

But windows has another root path (`\`, right?)

**Comment by jmaguirrei** [comment] 2016-02-17 13:00
@mastilver I am using babel 6.5.0 and working with beta version of Meteor 1.3, so I don´t think it´s good idea to release down babel for me now. I will be watching for news, thanks

**Comment by michaelzoidl** [comment] 2016-02-17 13:01
I also think the better solution is to update the plugin instead of downgrade the babel version... :)

**Comment by mastilver** [comment] 2016-02-17 13:03
@michaelzoidl I'm not 100% sure but if you create a test with at the beginning`path.sep = '\\'` it should do the job

**Comment by michaelzoidl** [comment] 2016-02-19 11:58
@mastilver ok i released a new version which should also support the windows-thing.. i found a [)module](http://npmjs.com/package/slash which handles this - i hope this fixes the issue.
I added no tests since travis decided [to not support windows](https://github.com/travis-ci/travis-ci/issues/216)

Can you test the new version? I've no windows system - at this time i've no idea if the slash-module is the solution.. so lets pray.

btw.. i found a explanation why windows handles the path-thing different on [stackoverflow](http://superuser.com/questions/176388/why-does-windows-use-backslashes-for-paths-and-unix-forward-slashes/176395#176395)

**Comment by mastilver** [comment] 2016-02-19 12:14
`slash` is nice, good find :+1: 

It's still failing, but you brought it to a better state
I can take it over for now ;)

**Comment by michaelzoidl** [comment] 2016-02-19 12:16
Mh.. damn, ok - then i close this issue, if you find the solution - just create a new issue or make a PR :)

**Comment by mastilver** [comment] 2016-02-19 12:17
alright, kind of weird to close the issue but up to you ;)

**Comment by michaelzoidl** [comment] 2016-02-19 12:19
hehe... i try to fix all issues, and for now - since you said the actual state is okey - i would pause to fix this issue.
But you're right - i don't close it..

**Comment by mastilver** [comment] 2016-02-19 12:20
> It's still failing, but you brought it to a better state

**Closed** 2016-05-31 07:41 UTC
