### ISSUE TITLE
Relative Path on Windows

### ISSUE THREAD

**Issue by cizmar** [michaelzoidl/babel-root-import#46] opened 2016-08-30 10:49 UTC
Hi guys,  

Great job with relative paths , but I have problem on my windows developer machine.  After update to version 4.1.1, I am not able to use this plugin. Relative paths are not correctly generated.

I assume problem is in helper.js line 36, where you controll first char to "/", whether sourcePath is absolute or not. Which I think is correct on unix machines, but on windows in variable sourcePath I have "C:\" ... 

If you could fix this problem, I would really appreciate it :-)

**Comment by BorjaRafols** [comment] 2016-09-05 12:11
Having the same issue here too. 

I expected the import to start resolving from the project root but it's actually nesting '../' from C://

I'm using windows too

**Comment by michaelzoidl** [comment] 2016-09-06 12:27
Hi, since i've no windows test env it's quite difficult for me to see if it's fixed.
I would appreciate if you try to fix it and make a PR :) 
Option B: you just write the "failing" tests and i update the module.

@ian-hutchinson if there is something i can help you just write it down / make a new PR :)

**Comment by ian-hutchinson** [comment] 2016-09-06 13:14
Hi Michael,

I think it was a bad PR - using a path method that gives varied results depending on platform. It fixed the Windows issue and all tests passed locally, but failed on CI due to it being a different platform.

I think the cause of the issue is the '/' prepended to the first argument of path.relative. On a Windows run, this'll make C:/path into /C:/path and the relative method produces the wrong result.

Think a fix is to just robust up the inputs to that method and make it platform-agnostic.

I'm pretty swamped over the next few days with a house move but I'll see if I can make time to take another look this weekend.

Best,
Ian

On 6 Sep 2016, at 13:27, Michael J. Zoidl <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, since i've no windows test env it's quite difficult for me to see if it's fixed.
I would appreciate if you try to fix it and make a PR :)
Option B: you just write the "failing" tests and i update the module.

@ian-hutchinson<https://github.com/ian-hutchinson> if there is something i can help you just write it down / make a new PR :)

-

**Comment by sivael** [comment] 2016-09-07 12:33
I've created a pull request that fixes it - 
https://github.com/michaelzoidl/babel-root-import/pull/49

**Comment by michaelzoidl** [comment] 2016-09-14 08:20
Sorry for the delay...
@sivael thanks for contributing, i merged and published a new version on npm `4.1.3` on npm :)

**Closed by michaelzoidl** 2016-09-14 08:20 UTC
